Formatted output of date and time variables
sbcgua/abap_mustache pull request #12
Opened 2023-05-25 23:13 UTC by kjetil-kilhavn

I just added the two simple cases for date and time variables, it will take a little more work to add all the numeric types.

2023-05-26 08:23 UTC, mbtools commented on src/zcl_mustache_render.clas.abap
> +    data lv_time type tims.
type d
type t 
😉

2023-05-26 10:45 UTC, sbcgua requested changes
@kjetil-kilhavn Thanks for the contribution. The change looks good. I agree with @mbtools comment, please change the time to internal ones. Also it would be great to add a small unit test that would cover the new feature. The simplest one possible would do.

2023-05-28 20:12 UTC, kjetil-kilhavn commented
I was a bit unsure about the unit test. First I added the new tests to the existing find_value() method, but I later decided to add a new method instead. I hope you don't mind me using a slightly different naming convention there.

2023-05-31 18:59 UTC, sbcgua approved these changes
Thank you ! :+1:
Merging ...

2023-05-31 18:59 UTC, merged