Care for https://me.sap.com/notes/3450531 Table X030L problem
sbcgua/abap_mustache pull request #17
Opened 2024-06-18 12:31 UTC by DerGuteWolf

get_ddic_header( ) is released and thus no syntax error but throws a runtime error, cf. https://me.sap.com/notes/3450531 .
Need to use steampunk way in steampunk and conventional way in non-steampunk.

2024-06-18 13:48 UTC, sbcgua commented
Looks good except the DTEL. Would it be possible to avoid creating a new DDIC type? Especially since it is used in test only?

2024-06-18 17:11 UTC, DerGuteWolf commented
I know, but for testing if a timestamp ddic type works I need a ddic type. I could try dynamically creating one and deleting it afterwards, but would be very cumbersome..

2024-06-18 18:05 UTC, larshp commented
try https://abapedia.org/steampunk-2305-api-intersect-702/timestampl.dtel.html or https://abapedia.org/steampunk-2305-api-intersect-702/timestamp.dtel.html, both exist in 702 and is released in steampunk

also more examples welcome in https://github.com/heliconialabs/steampunkification

2024-06-19 04:33 UTC, DerGuteWolf commented
Hi @larshp,
thanks for the hint and I know those two, but they are already dealt with in the respective first comparison. I need

2024-06-19 07:24 UTC, sbcgua commented
Adding a DDIC object immediately makes this package heavier. I think it is even better to skip this particular UT than adding a UT-specific and the only DDIC object.

Or targeting the UT to 702 - so create variable dynamically with some standard named type, catching the exception in the steampunk env and treating it as tolerable.

2024-06-19 09:58 UTC, DerGuteWolf commented
The problem is that I need this at least to be syntax error free in steampunk - use of unreleased stuff is a syntax error...

2024-06-19 09:59 UTC, DerGuteWolf commented
I will try once more to find a suitable alternative however

2024-06-19 10:16 UTC, DerGuteWolf commented
![image](https://github.com/sbcgua/abap_mustache/assets/638512/4af0a7ae-4508-41a4-80d4-873ce4a52275)
Domain TZNTSTMPL h has a few more releases uses in steampunk, however none of these are available in 750

2024-06-19 10:21 UTC, DerGuteWolf commented
I have an idea: I will dynamically create a variable, steampunk way with steampunk released DTEL and non-steampunk way with DTEL available in at least in 750. Will however take some time.... let's leave this pull request open until then

2024-06-19 12:48 UTC, DerGuteWolf commented
ok, now without ddic and with dynamic unit test. I am not sure if the unit test could be simplified a bit more, but it works now in 750 and steampunk. I also added performance improvement for dtel TZNTSTMPS/TZNTSTMPL and a unit test.

2024-06-23 14:46 UTC, sbcgua requested changes
Looks good now. Just downport the syntax to 702 and it's good to go. Thank you !

2024-06-23 14:46 UTC, sbcgua commented on src/zcl_mustache_render.clas.testclasses.abap
> +        data(lv_elem) = cl_abap_datadescr=>describe_by_name( 'BALTIMSTMP' ).
740+

2024-06-23 14:46 UTC, sbcgua commented on src/zcl_mustache_render.clas.testclasses.abap
> +        DATA(lt_comp) = VALUE cl_abap_structdescr=>component_table( ( name = 'TIMESTAMP_DDIC' type = CAST #( lv_elem ) ) ).
740+

2024-06-23 16:16 UTC, DerGuteWolf commented
Ok, will do that. I have no 702 system currently. Wasn't there some possibility to check for older syntax in a newer system?

2024-06-24 09:43 UTC, sbcgua approved these changes
Works well on 731. :+1:

Thanks again ! Merging ...

2024-06-24 09:43 UTC, merged